### ISSUE TITLE
Docker: add tally-web service and resolve hot module reloading

### ISSUE THREAD

**Issue by JdgaleTorre** [la5ta/tally#2]
Add tally-web service and make the hot module reloading work.

**Comment by JdgaleTorre** [comment]
I already have some changes to make it work, but I don't understand one thing:
Why in the docker-compose the volume of tally-web is:
`- ./tally-web/:/webroot/default`
I found that for docker see the changes you have to point the WORKDIR of dockerfile something like:
`- ./tally-web/:/root/app`,

I want to know this to commit the changes.

**Comment by pipa** [comment]
You are correct! I updated these paths on my branch for relay-modern([you can take a look here](https://github.com/la5ta/tally-web/blob/relay-modern/Dockerfile#L11)), by accepting an environment variable for the correct path so we can control this from the docker-compose or something like that. I think you can commit that for it not to be a blocker for you since I think it'll take a bit longer for me to push the branch with the fix
